Repository Alfresco/alfresco-tas-restapi, pull requests merged in 2022-09, with the labels that each got.

#241 Upgrade tas-utility version to use latest TestNG.
  pom.xml
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: reviewed-approved

#247 ACS-3363 Add inheritedBy to rule set.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
Labels: PR: partially-approved

#248 ACS-3364 ACS-3365 ACS-3366 Add extra fields to rule set.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
Labels: PR: partially-approved

#252 Fix setter and getter naming for GET rule set fields.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
Labels: PR: partially-approved

#253 ACS-3359 Rename boolean fields.
  src/main/java/org/alfresco/rest/model/RestRuleModel.java
Labels: PR: partially-approved

#255 ACS-3560 Add custom embedded workflow to entitlements model
  src/main/java/org/alfresco/rest/model/RestEntitlementsInfoModel.java
Labels: PR: reviewed-approved

#258 ACS-3601: Add unlink request method
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: reviewed-approved

#256 ACS-3376 ACS-3377 Support GET and PUT rule id list.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: partially-approved

#259 ACS-3601 add e2e unlink functionality
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: unreviewed

#257 ACS-3525: API for manual triggering rules on a folder
  src/main/java/org/alfresco/rest/core/RestRequest.java
  src/main/java/org/alfresco/rest/core/assertion/ModelAssertion.java
  src/main/java/org/alfresco/rest/model/RestRuleExecutionBodyModel.java
  src/main/java/org/alfresco/rest/model/RestRuleExecutionModel.java
  src/main/java/org/alfresco/rest/requests/Node.java
  src/test/java/org/alfresco/rest/core/RestRequestTest.java
Labels: PR: unreviewed
