Repository Alfresco/alfresco-tas-restapi, pull requests merged in 2022-08, with the labels that each got.

#216 ACS-3360 TAS endpoints for GET rule sets.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: partially-approved

#217 ACS-3360 GET APIs for rule sets E2E tests.
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: partially-approved

#218 ACS-3362 Add owningFolder field to rule set.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: partially-approved

#220 Move all versions under the rest-assured.version, update it to 5.1.1
  pom.xml
Labels: PR: unreviewed

#221 ACS-3361 Support for inclusionType.
  src/main/java/org/alfresco/rest/model/RestRuleSetModel.java
Labels: PR: partially-approved

#219 ACS-3351 Upgrade to Java 17
  .travis.yml
Labels: PR: partially-approved

#222 ACS-3358 Remove demo tests.
  .travis.yml
  src/test/java/org/alfresco/rest/.keepme
  src/test/java/org/alfresco/rest/demo/RestDemoTests.java
  src/test/java/org/alfresco/rest/demo/SampleCommentsTests.java
  src/test/java/org/alfresco/rest/demo/SamplePeopleTests.java
  src/test/java/org/alfresco/rest/demo/SampleSitesTests.java
  src/test/java/org/alfresco/rest/demo/workshop/RestApiDemoTests.java
  src/test/java/org/alfresco/rest/demo/workshop/RestApiWorkshopTests.java
Labels: PR: partially-approved

#223 ACS-3358 Support specifying include.
  pom.xml
  src/main/java/org/alfresco/rest/core/RestWrapper.java
  src/main/java/org/alfresco/rest/requests/ModelRequest.java
  src/test/java/org/alfresco/rest/core/RestWrapperTest.java
  src/test/java/org/alfresco/rest/requests/ModelRequestTest.java
Labels: PR: partially-approved

#224 ACS-3358 Refactor ModelRequest to cope with more parameters than tokens in the URL.
  src/main/java/org/alfresco/rest/core/RestRequest.java
  src/test/java/org/alfresco/rest/core/RestRequestTest.java
Labels: PR: partially-approved

#227 ACS-3358 We no longer need to explicitly specify "?{parameters}".
  src/main/java/org/alfresco/rest/requests/Node.java
  src/main/java/org/alfresco/rest/requests/syncServiceAPI/Sync.java
  src/test/java/org/alfresco/rest/model/ModelAssertionTest.java
Labels: PR: partially-approved

#228 ACS-3358 Automatically include extra params.
  src/main/java/org/alfresco/rest/core/RestRequest.java
  src/main/java/org/alfresco/rest/core/RestWrapper.java
  src/main/java/org/alfresco/rest/requests/Node.java
Labels: PR: partially-approved

#230 ACS-3353: POST support for "other fields"
  src/main/java/org/alfresco/rest/core/assertion/ModelAssertion.java
  src/main/java/org/alfresco/rest/model/RestActionBodyExecTemplateModel.java
  src/main/java/org/alfresco/rest/model/RestCompositeConditionDefinitionModel.java
  src/main/java/org/alfresco/rest/model/RestRuleModel.java
  src/main/java/org/alfresco/rest/model/RestSimpleConditionDefinitionModel.java
  src/test/java/org/alfresco/rest/model/ModelAssertionTest.java
Labels: PR: unreviewed

#231 ACS-3353: POST support for "other fields"
  src/main/java/org/alfresco/rest/model/RestRuleModel.java
Labels: PR: reviewed-approved

#235 ACS-3280 Get/Set Rules Inheritance.
  src/main/java/org/alfresco/rest/model/RestRuleSettingsModel.java
  src/main/java/org/alfresco/rest/requests/Node.java
  src/main/java/org/alfresco/rest/requests/RuleSettings.java
Labels: PR: partially-approved
